import yfinance as yf
import pandas as pd

stocks = [
   "IFCI.NS", 
"AFFLE.NS", 
"TECHNOE.NS", 
"CGPOWER.NS", 
"ZENSARTECH.NS", 
"NTPCGREEN.NS", 
"DATAPATTNS.NS", 
"GMDCLTD.NS", 
"RRKABEL.NS", 
"VTL.NS", 
"SCI.NS", 
"MEDANTA.NS", 
"NETWEB.NS", 
"OLECTRA.NS", 
"BALRAMCHIN.NS", 
"CROMPTON.NS", 
"GPIL.NS", 
"MOTILALOFS.NS", 
"AGARWALEYE.NS", 
"DIXON.NS", 
"SWIGGY.NS", 
"HBLENGINE.NS", 
"ELGIEQUIP.NS", 
"NEULANDLAB.NS", 
"JWL.NS", 
"TIINDIA.NS", 
"ESCORTS.NS", 
"KAYNES.NS", 
"IDBI.NS", 
"TITAGARH.NS", 
"LEMONTREE.NS", 
"SYRMA.NS", 
"MAZDOCK.NS", 
"NIACL.NS", 
"KPRMILL.NS", 
"IREDA.NS", 
"HUDCO.NS", 
"ASTERDM.NS", 
"RAILTEL.NS", 
"SCHNEIDER.NS", 
"BLS.NS", 
"SOLARINDS.NS", 
"SUZLON.NS", 
"TRIDENT.NS", 
"BIKAJI.NS", 
"JBMA.NS", 
"DBREALTY.NS", 
"GRSE.NS", 
"ONESOURCE.NS", 
"NCC.NS", 
"WHIRLPOOL.NS", 
"AFCONS.NS", 
"BEL.NS", 
"JSWINFRA.NS", 
"MINDACORP.NS", 
"FIVESTAR.NS", 
"TARIL.NS", 
"JUBLFOOD.NS", 
"PRAJIND.NS", 
"PGHH.NS", 
"IRFC.NS", 
"ANANTRAJ.NS", 
"ITI.NS", 
"VMM.NS", 
"NYKAA.NS", 
"AMBUJACEM.NS", 
"WELSPUNLIV.NS", 
"ZENTEC.NS", 
"INDIAMART.NS", 
"BHARATFORG.NS", 
"FACT.NS", 
"TMPV.NS", 
"IRCON.NS", 
"SUNPHARMA.NS", 
"BHEL.NS", 
"FINCABLES.NS", 
"SAREGAMA.NS", 
"THELEELA.NS", 
"ATHERENERG.NS", 
"SJVN.NS", 
"APLLTD.NS", 
"HEROMOTOCO.NS", 
"MAPMYINDIA.NS", 
"HAL.NS", 
"JYOTICNC.NS", 
"CRISIL.NS", 
"M&M.NS", 
"JYOTHYLAB.NS", 
"IRCTC.NS", 
"POWERGRID.NS", 
"DABUR.NS", 
"ELECON.NS", 
"AMBER.NS", 
"IRB.NS", 
"BATAINDIA.NS", 
"TATACOMM.NS", 
"KAJARIACER.NS", 
"ALOKINDS.NS", 
"METROPOLIS.NS", 
"RCF.NS", 
"TATAPOWER.NS", 
"KALYANKJIL.NS", 
"RITES.NS", 
"WAAREEENER.NS", 
"PRESTIGE.NS", 
"THERMAX.NS", 
"DELHIVERY.NS", 
"CONCOR.NS", 
"MRF.NS", 
"SUMICHEM.NS", 
"IGIL.NS", 
"MAXHEALTH.NS", 
"SRF.NS", 
"TEJASNET.NS", 
"RVNL.NS", 
"JPPOWER.NS", 
"ANANDRATHI.NS", 
"BAJAJHFL.NS", 
"WELCORP.NS", 
"ACC.NS", 
"STARHEALTH.NS", 
"LTTS.NS", 
"CARBORUNIV.NS", 
"CHAMBLFERT.NS", 
"ARE&M.NS", 
"INDIACEM.NS", 
"ABFRL.NS", 
"IKS.NS", 
"TIMKEN.NS", 
"LATENTVIEW.NS", 
"LT.NS", 
"APLAPOLLO.NS", 
"ENGINERSIN.NS", 
"MARUTI.NS", 
"ADANIENSOL.NS", 
"TTML.NS", 
"FINPIPE.NS", 
"IEX.NS", 
"BHARTIHEXA.NS", 
"MANYAVAR.NS", 
"COCHINSHIP.NS", 
"HEG.NS", 
"KOTAKBANK.NS", 
"MGL.NS", 
"KSB.NS", 
"NLCINDIA.NS", 
"ASTRAL.NS", 
"ACMESOLAR.NS", 
"TBOTEK.NS", 
"INDIGO.NS", 
"ERIS.NS", 
"CEATLTD.NS", 
"HDFCAMC.NS", 
"BBTC.NS", 
"BLUEDART.NS", 
"TORNTPHARM.NS", 
"GODREJIND.NS", 
"RBLBANK.NS", 
"SUPREMEIND.NS", 
"EXIDEIND.NS", 
"RELIANCE.NS", 
"HEXT.NS", 
"ACE.NS", 
"CERA.NS", 
"PGEL.NS", 
"GODREJAGRO.NS", 
"PVRINOX.NS", 
"BEML.NS", 
"FORCEMOT.NS", 
"BRITANNIA.NS", 
"INDHOTEL.NS", 
"DALBHARAT.NS", 
"JBCHEPHARM.NS", 
"EICHERMOT.NS", 
"AIIL.NS", 
"CAMS.NS", 
"KIRLOSBROS.NS", 
"ONGC.NS", 
"ABREL.NS", 
"SBFC.NS", 
"ADANIGREEN.NS", 
"NAVINFLUOR.NS", 
"TATACONSUM.NS", 
"NHPC.NS", 
"TATAELXSI.NS", 
"HAVELLS.NS", 
"PCBL.NS", 
"CAPLIPOINT.NS", 
"PFIZER.NS", 
"RKFORGE.NS", 
"EIHOTEL.NS", 
"DEEPAKFERT.NS", 
"CHOLAHLDNG.NS", 
"HYUNDAI.NS", 
"FORTIS.NS", 
"JSWCEMENT.NS", 
"SHREECEM.NS", 
"CANBK.NS", 
"TATATECH.NS", 
"TATACHEM.NS", 
"ICICIGI.NS", 
"INDGN.NS", 
"ADANIPOWER.NS", 
"OLAELEC.NS", 
"HONASA.NS", 
"BLUESTARCO.NS", 
"SWANCORP.NS", 
"HDFCBANK.NS", 
"AUBANK.NS", 
"M&MFIN.NS", 
"ICICIBANK.NS", 
"BAJAJ-AUTO.NS", 
"SONACOMS.NS", 
"ULTRACEMCO.NS", 
"NAUKRI.NS", 
"SYNGENE.NS", 
"CRAFTSMAN.NS", 
"BERGEPAINT.NS", 
"JUBLINGREA.NS", 
"SIGNATURE.NS", 
"TORNTPOWER.NS", 
"JINDALSTEL.NS", 
"INDUSINDBK.NS", 
"RECLTD.NS", 
"PNBHOUSING.NS", 
"PAGEIND.NS", 
"GRAVITA.NS", 
"BAJFINANCE.NS", 
"HAPPSTMNDS.NS", 
"GICRE.NS", 
"EMCURE.NS", 
"KPIL.NS", 
"WIPRO.NS", 
"DMART.NS", 
"PTCIL.NS", 
"ECLERX.NS", 
"LLOYDSME.NS", 
"ABLBL.NS", 
"PATANJALI.NS", 
"ATGL.NS", 
"ADANIPORTS.NS", 
"DLF.NS", 
"NTPC.NS", 
"YESBANK.NS", 
"HFCL.NS", 
"BRIGADE.NS", 
"BLUEJET.NS", 
"GODIGIT.NS", 
"CUMMINSIND.NS", 
"NAVA.NS", 
"UTIAMC.NS", 
"LICI.NS", 
"POLYMED.NS", 
"GLAND.NS", 
"DEVYANI.NS", 
"PPLPHARMA.NS", 
"APARINDS.NS", 
"PHOENIXLTD.NS", 
"SBIN.NS", 
"LTF.NS", 
"MARICO.NS", 
"AEGISVOPAK.NS", 
"BALKRISIND.NS", 
"NBCC.NS", 
"ITC.NS", 
"JIOFIN.NS", 
"FIRSTCRY.NS", 
"BHARTIARTL.NS", 
"PREMIERENE.NS", 
"DRREDDY.NS", 
"RAINBOW.NS", 
"ICICIPRULI.NS", 
"CASTROLIND.NS", 
"JSWENERGY.NS", 
"COLPAL.NS", 
"GMRAIRPORT.NS", 
"TRIVENI.NS", 
"AAVAS.NS", 
"COHANCE.NS", 
"DOMS.NS", 
"HDFCLIFE.NS", 
"GVT&D.NS", 
"HINDUNILVR.NS", 
"FEDERALBNK.NS", 
"MANKIND.NS", 
"SBICARD.NS", 
"CHOICEIN.NS", 
"POWERINDIA.NS", 
"POLYCAB.NS", 
"AWL.NS", 
"APTUS.NS", 
"SBILIFE.NS", 
"SAIL.NS", 
"GLAXO.NS", 
"ABBOTINDIA.NS", 
"AARTIIND.NS", 
"OBEROIRLTY.NS", 
"CONCORDBIO.NS", 
"SHRIRAMFIN.NS", 
"JSWSTEEL.NS", 
"ASIANPAINT.NS", 
"NIVABUPA.NS", 
"UNOMINDA.NS", 
"SUNTV.NS", 
"HCLTECH.NS", 
"MOTHERSON.NS", 
"CAMPUS.NS", 
"CHOLAFIN.NS", 
"DIVISLAB.NS", 
"CHENNPETRO.NS", 
"ASAHIINDIA.NS", 
"KFINTECH.NS", 
"VIJAYA.NS", 
"LALPATHLAB.NS", 
"ZYDUSLIFE.NS", 
"TECHM.NS", 
"LTIM.NS", 
"TCS.NS", 
"TVSMOTOR.NS", 
"AJANTPHARM.NS", 
"ALKYLAMINE.NS", 
"TRITURBINE.NS", 
"CIPLA.NS", 
"POONAWALLA.NS", 
"HSCL.NS", 
"LINDEINDIA.NS", 
"ADANIENT.NS", 
"UNIONBANK.NS", 
"NEWGEN.NS", 
"UPL.NS", 
"APOLLOHOSP.NS", 
"KIMS.NS", 
"APOLLOTYRE.NS", 
"TRENT.NS", 
"PERSISTENT.NS", 
"ZFCVINDIA.NS", 
"3MINDIA.NS", 
"VBL.NS", 
"PAYTM.NS", 
"COROMANDEL.NS", 
"OIL.NS", 
"360ONE.NS", 
"ITCHOTELS.NS", 
"FSL.NS", 
"FLUOROCHEM.NS", 
"TATASTEEL.NS", 
"PFC.NS", 
"ASHOKLEY.NS", 
"MSUMI.NS", 
"LTFOODS.NS", 
"ASTRAZEN.NS", 
"PIDILITIND.NS", 
"ETERNAL.NS", 
"LICHSGFIN.NS", 
"GRASIM.NS", 
"EMAMILTD.NS", 
"GESHIP.NS", 
"AXISBANK.NS", 
"NH.NS", 
"HONAUT.NS", 
"GODREJCP.NS", 
"BOSCHLTD.NS", 
"BASF.NS", 
"BPCL.NS", 
"BAYERCROP.NS", 
"KEI.NS", 
"ENRIN.NS", 
"NMDC.NS", 
"MFSL.NS", 
"MAHSEAMLES.NS", 
"JKTYRE.NS", 
"SONATSOFTW.NS", 
"PETRONET.NS", 
"JKCEMENT.NS", 
"USHAMART.NS", 
"ABSLAMC.NS", 
"GILLETTE.NS", 
"OFSS.NS", 
"SARDAEN.NS", 
"COFORGE.NS", 
"REDINGTON.NS", 
"IGL.NS", 
"IDFCFIRSTB.NS", 
"TATAINVEST.NS", 
"BAJAJFINSV.NS", 
"BAJAJHLDNG.NS", 
"MPHASIS.NS", 
"AKZOINDIA.NS", 
"WOCKPHARMA.NS", 
"JINDALSAW.NS", 
"POLICYBZR.NS", 
"PIIND.NS", 
"NATCOPHARM.NS", 
"GSPL.NS", 
"ATUL.NS", 
"J&KBANK.NS", 
"UBL.NS", 
"ABCAPITAL.NS", 
"CESC.NS", 
"HOMEFIRST.NS", 
"SOBHA.NS", 
"MANAPPURAM.NS", 
"GODREJPROP.NS", 
"UCOBANK.NS", 
"INDUSTOWER.NS", 
"SCHAEFFLER.NS", 
"CCL.NS", 
"BIOCON.NS", 
"SHYAMMETL.NS", 
"CHALET.NS", 
"SAPPHIRE.NS", 
"ZEEL.NS", 
"ALKEM.NS", 
"SUNDRMFAST.NS", 
"LUPIN.NS", 
"CENTRALBK.NS", 
"CYIENT.NS", 
"VOLTAS.NS", 
"VENTIVE.NS", 
"LODHA.NS", 
"ENDURANCE.NS", 
"DCMSHRIRAM.NS", 
"NAM-INDIA.NS", 
"DEEPAKNTR.NS", 
"NUVAMA.NS", 
"NUVOCO.NS", 
"IDEA.NS", 
"SAGILITY.NS", 
"PNB.NS", 
"RPOWER.NS", 
"JUBLPHARMA.NS", 
"NESTLEIND.NS", 
"GUJGASLTD.NS", 
"CENTURYPLY.NS", 
"COALINDIA.NS", 
"SAILIFE.NS", 
"JMFINANCIL.NS", 
"INOXWIND.NS", 
"IOC.NS", 
"AKUMS.NS", 
"AADHARHFC.NS", 
"GODFRYPHLP.NS", 
"SIEMENS.NS", 
"GAIL.NS", 
"INFY.NS", 
"HINDPETRO.NS", 
"MAHSCOOTER.NS", 
"TITAN.NS", 
"IOB.NS", 
"SAMMAANCAP.NS", 
"IPCALAB.NS", 
"CDSL.NS", 
"BANKBARODA.NS", 
"BSOFT.NS", 
"INDIANB.NS", 
"GRANULES.NS", 
"LAURUSLABS.NS", 
"CGCL.NS", 
"NSLNISP.NS", 
"ABB.NS", 
"RHIM.NS", 
"SUNDARMFIN.NS", 
"INOXINDIA.NS", 
"GLENMARK.NS", 
"CREDITACC.NS", 
"MAHABANK.NS", 
"UNITDSPR.NS", 
"MMTC.NS", 
"BANDHANBNK.NS", 
"IIFL.NS", 
"KPITTECH.NS", 
"RAMCOCEM.NS", 
"AUROPHARMA.NS", 
"BDL.NS", 
"AIAENG.NS", 
"CANFINHOME.NS", 
"VGUARD.NS", 
"BSE.NS", 
"BANKINDIA.NS", 
"EIDPARRY.NS", 
"CUB.NS", 
"JSL.NS", 
"GRAPHITE.NS", 
"KEC.NS", 
"VEDL.NS", 
"AEGISLOG.NS", 
"MRPL.NS", 
"KIRLOSENG.NS", 
"ANGELONE.NS", 
"CLEAN.NS", 
"RADICO.NS", 
"HINDALCO.NS", 
"KARURVYSYA.NS", 
"RELINFRA.NS", 
"MUTHOOTFIN.NS", 
"INTELLECT.NS", 
"NATIONALUM.NS", 
"HINDZINC.NS", 
"HINDCOPPER.NS", 
"MCX.NS"
]

def calculate_vwap(df):
    tp = (df["High"] + df["Low"] + df["Close"]) / 3
    return (tp * df["Volume"]).cumsum() / df["Volume"].cumsum()

print("\n🔍 NSE INTRADAY SCANNER (5-MIN)\n")

for symbol in stocks:
    try:
        df = yf.download(
            symbol,
            interval="5m",
            period="5d",
            progress=False
        )

        if df.empty:
            continue

        # FIX: flatten columns (NSE quirk)
        if isinstance(df.columns, pd.MultiIndex):
            df = df.droplevel(1, axis=1)

        if len(df) < 60:
            continue

        # Indicators
        df["EMA9"]  = df["Close"].ewm(span=9, adjust=False).mean()
        df["EMA21"] = df["Close"].ewm(span=21, adjust=False).mean()
        df["EMA50"] = df["Close"].ewm(span=50, adjust=False).mean()
        df["VWAP"]  = calculate_vwap(df)

        last = df.iloc[-1]

        # Scalar values (VERY IMPORTANT)
        price = float(last["Close"])
        ema9  = float(last["EMA9"])
        ema21 = float(last["EMA21"])
        ema50 = float(last["EMA50"])
        vwap  = float(last["VWAP"])

        # ⏱ Time
        candle_time = last.name

        # 📊 Volume spike filter
        avg_vol  = df["Volume"].iloc[-21:-1].mean()
        curr_vol = df["Volume"].iloc[-1]
        volume_spike = curr_vol > (1.5 * avg_vol)

        if not volume_spike:
            continue  # skip low-interest candles

        # BUY
        if price > ema9 > ema21 > ema50 and price > vwap:
            sl = min(ema21, vwap)
            target = price + 2 * (price - sl)
            print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
            print(f"SYMBOL : {symbol}")
            print(f"TIME   : {candle_time}")
            print(f"PRICE  : {round(price,2)}")
            print("ACTION : BUY")
            print(f"SL     : {round(sl,2)}")
            print(f"TARGET : {round(target,2)}")
            print("RR     : 1:2")
            print("VOL    : SPIKE ⬆︎")

        # SHORT
        elif price < ema9 < ema21 < ema50 and price < vwap:
            sl = max(ema21, vwap)
            target = price - 2 * (sl - price)
            print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
            print(f"SYMBOL : {symbol}")
            print(f"TIME   : {candle_time}")
            print(f"PRICE  : {round(price,2)}")
            print("ACTION : SHORT")
            print(f"SL     : {round(sl,2)}")
            print(f"TARGET : {round(target,2)}")
            print("RR     : 1:2")
            print("VOL    : SPIKE ⬇︎")

    except Exception as e:
        print(f"{symbol} ❌ ERROR: {e}")

print("\n✅ Scan complete\n")
